---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCNynVSYOtm6uD0AYpNTro7LmA9MDVZBMtoINfVp4Uw1GUNUu6O4pnv83aPdIcZS8uwFsU87I93PClDPa6OwdyUGtfn6ju9mXA3uvYKKGpjiyYcmXMG/sx22sIRD62MLDmAX+F0qjX0BBNS5ivf+p6v6NvDaptpKp0lbjXMZVEkR+bjfZuDW5tR5jAslYM+YpUJKqULCdr+3RHN/E7QnQBnWLlMNGbBtNh7GczIGBSUBq2BggeWDVQGJSZ9BKs2Qx6wUMJuAkkLa19PHFQoYcQUmKoT6XZkrJ62Nwcu+aMK63PPUSNkJtcDf4XWuc109D1nGgcupWgyJKxixcpUeSyYu2IxzGnZvdxbxFZUSJSE4h2P+jhF7SrTRQ9+pEFwtDgs01DnKO8OyC9ixETv+xy09WLdutkJF83Jvp8+7P0mxQqZG9sW61HxxKr+2gpOjy2vhf6KboTRKcOblEFJUnXPg7XK1dBmKO4jRk+Q+WKpxT6OhgEPRqw3aBrW8riF7+v1gu0+pithplqvPoSPywWnV16gZUcWKu623Pb8HLu4D75NNKrpZ+ifHS3O4iHaUO6y1t/FKyooazG0Ga3A9Hdl59sJ22Qs5VSHwxJxjyn0PQ2F+9QxUUFo/qNaa79WXsZA163AR6o8pvC2CU34kSTSRcDc2EzxUKOaoe9TOAKatD5j/T1AUHOYq3RFRnnBJ5MGPaIJ3Y63NaJAI4TR4F5v/IyEmPif2DfJBLSGuHlHFaimVz+p6oZNNwdav46CQ/ur/mqd4LSUFrLgO6w9nI1YyNBxbbk9i185zwk6yOj44zM9h6+wgekwsxeN5Q6ThxIrDOIDFvsJ8C5rDomgxU+6VCLMw1kCP97b9unarKGCN8NmItVxkNuArf3U9wjlPX741kYzKMlzJKpq+EbVE/PWjLcbqZ+RSaY/Euw=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
