---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAwvZ1REcb1XV3rwylrwPz6HTtH4PvlsF9SKeFlcaMAlXVJ0HWadrQZtLmPHQGs7Eqa4YH9a18fJPyUXYYv7BX0YCvm541yGkbSCvFfJ7vcfdvSpAq8lhXVwugbn6sxc5WPWhj4LeGY+fGhfVPCHEXdvSLoE7sck9oGpYhrxdwdauZ2cYlnHMemgPVRK0vGpBACFCfizmOMJZd051l0FiBm4d/t7MR7OLAsTJFlLlqVaKjlOqC/3OxQd1LfWuB0QzowyD2cAi9PxcgT8ng6iG5aYp2P+PlaDbUF0qU6ZCm/TjftyItXRZoWevC8XnrObCHgKc0tPo250tyJ5mRVJHFCpvzQIupa43ww5MQDsWO3ZZ/vQEHv7xHeBj/XutSRNSGA4WTzhGjO4ONMSIK/1moR0xU4pv9PBcsWXP2GPsnrg3Undm7WnGSGqN4gc5nSL3+wCveS6a/oINgcw71hl3suiJORh30/A0C4QJMfEde/02KY8cHM4UeSFv1n23RuHGJAEPRTOGhXzuMN+wj9kDRv0lxDqY8sfTwGzAYy43eFIplzzaetAuCBCBEoiMCqKaeizMc5IH2NyWMfd9x/6tfnuKvGFth2ACrm2lfEjlrr+SM6cWYmX3IBvzYGrLI//iLWa+KJbWaCfKpxvQNekzkFzF8fOliV5FvI8Co6kBREZnZRy7xtuYE+ZYCBblu18lOvHngIz8OhvJM4Y4dz+qnao/tbma2DLIhdiAnD4LKTTBaQiytRzxFvA4hYrCplOw3754GzRHc6mx4d0QGVcMyivtP5n97ZXb7px/8Vh7wkPwoBkumP8N00ZHVjCXq3T6KRigqLbCYrx/JvHB3WCN345XNdRJMO4pWG3yWoEs1WErsXELO4JecwULdvWU6kInp0f0BqGyoT/YoxsNlMoBRgnvEVZzxlp8rm9m8=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
