apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: inventory-service
    env: dev
spec:
  type: ClusterIP
  selector:
    app: inventory-service
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
