apiVersion: v1
kind: Service
metadata:
  name: __SERVICE__
  labels:
    app: __SERVICE__
    env: prod
spec:
  type: ClusterIP
  selector:
    app: __SERVICE__
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: __SERVICE__-canary
  labels:
    app: __SERVICE__
    env: prod
    role: canary
spec:
  type: ClusterIP
  selector:
    app: __SERVICE__
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
