apiVersion: v1
kind: Service
metadata:
  name: notifications-service
  labels:
    app: notifications-service
    env: prod
spec:
  type: ClusterIP
  selector:
    app: notifications-service
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service-canary
  labels:
    app: notifications-service
    env: prod
    role: canary
spec:
  type: ClusterIP
  selector:
    app: notifications-service
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
