---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCgWt7soML+ua2DMsaLD48H2hQykks4BZuy6M/hSV5Rmgbf2f8aPbzSoOp62fG9jgX3IbYZZ8tWhUuDzRNo8y1rZSBkXnDn7P6zAmB0v+ylCdQ3s6v655zPMjRNNDvFQa+TUE5Tc+nY730T/a9eKOczMi/FWEHD9WsUuNaJUMllz5X5bgfVy/8uxlFClEHXCc2gevBtjp2GquzT8bFU5Dx0BvZfnWkNha+YjWb4AfH6pFGDDZjBJyRgc8RrFAVa9HcdgFwGQQNMRlzuRR9yHFAvPGSIeArQOXI1tF9yIJlAahd9Y/pLu4X9aJY+o/KDqVDAOk5IYU2pEt8/IOlwyVNovRyHzl+J/os4hTCmadksBcGs5LSorQLXjODmrj+R0BwdF63HRXu7bgnWxAbNzOZz5KysRULfY+8TcSWUlGJJQM5RlyMQhSXU7os5A/1LzWKzSQ5mZihS138VP0oosejmmMObe9z4+OHbpPBO11wzbE2Vu9AVogjMJRnH5bZPe+GFS0ZoL3tA9iYbITzLGY4Wj1slQfc+R8+dz2bddYPU8vOTE0K+AXOcMr/AiMAY9egU9Ius9JPz2L/Q/o08Rw6BOvddWLnlRmiCsNFWKgHfwflMiUH4TUmJgayIJzBElJZ1DKJk6wMSWxyEWixcy3ZwRexf0HbqYSeClwtA71HKtqcEeZhU86Yjikf0Ym0/f3mlg7uQTwEGWUejMg5UM3gL09nIcsx7yuPedlIGi2+7CR6Ftx4tqPx3zGaLHlXiiWox1AR9vXMiti7vStjNXJB47GRlS0xJO5JBuDPHFWxchT5nR18FCbZ6Am0X3AQCkWTuRGR1/P9Sa7LGIWgQeMK03+g/oiRkXyjXZHqTY+oWedXRNw9tPlnn7zeXPhbAcRmHJXIW0npfuWHtDseEUf6SQNM//r/esKOPI7A=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
