apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: health-check
spec:
  args:
  - name: service-name
  metrics:
  - name: health-check
    interval: 30s
    successCondition: result == "true"
    failureLimit: 3
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              restartPolicy: Never
              containers:
              - name: curl
                image: curlimages/curl:8.9.1
                command:
                - sh
                - -c
                - |
                  response=$(curl -s -o /dev/null -w "%{http_code}" http://{{args.service-name}}:8080/actuator/health)
                  if [ "$response" -eq 200 ]; then
                    echo "true"
                  else
                    echo "false"
                  fi
