apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- rollout.yaml
- service.yaml
- analysis-template.yaml
- sealed-secret-ghcr.yaml

images:
- name: ghcr.io/itayna/java-sample-app
  newTag: latest
