apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- deployment.yaml
- service.yaml

images:
- name: ghcr.io/itayna/java-sample-app
  newTag: 85cadd62abe7
