apiVersion: v1
kind: Service
metadata:
  name: java-sample-app
  labels:
    app: java-sample-app
    env: dev
spec:
  type: NodePort
  selector:
    app: java-sample-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
