apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:itayna/terasky-platform-ha.git
    targetRevision: main
    path: environments/dev/inventory-service
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
