apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- deployment.yaml
- service.yaml
- sealed-secret-ghcr.yaml

images:
- name: ghcr.io/itayna/java-sample-app
  newTag: fd6a5e449a8e
