---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgB9xAkrlQySLkvvfEPej3ds+O+z7VCfkFVDe5H+UClvTjf4UZyoRe6mTHPrW0d0Kvfrjv6nPbsmExLs4oboDsHlraVj2Teowx5ctMcgUYBNhljg/F89uh+W47sGds+vDJ77xHspJEmhQUSRu7Kuafh0Z5vy+PEAg+BNhQ5L5FB1B7+MIr37lfkRrOySML8bpk44NKbssyzmnCn6ovJ+oDWrMiQpF59dYiw1nmKVkcA9b8SLzVfMQiTQM0q0COfYBQ566CI+wuFlwTK11nKlGO0FaaAMOKDMMmeAL4WnGoNjyXsWEMgLHfmy/Tq5Tb3xjjSZyk4hv5SyLnxKeCoUpbOM4TTFPWWE/HTkzfJCtyAkGBSFpDljFfm2DhKX7wRfWZqarUtEgYjOQjcyWr5EvEh7EYtS4TSellNu0fXX44BPsOMW0nIrPgw8CjY987mlvi+25TlU2n0zNZP8JeNDG9kFe6otyXa5+eF9Fe3qlfsq8KhPhOhxqZumYdw2VGhpQt7ZzAoshiYtHUrPd9m8uK4x/piyaMdWfw8eZqCcdtgy2jNme0KMBnAPTIU/MmoT+jJl9Igv5tfROAzAvkODN182gnZ1OoLMWPLe2uDR3eKhXOLiMA4EvJynbE25PNpyY+66qfBTiasDb4EqJiTIVhSK6FxW2FyWXcNN8Neq9vltRPPQ1Pgi5zRAeUXk9551s//6nydhmsQjxUtU9rVO1rhJFmixmn2zT4hu9AAcPVY90FK2djbshCgzHzhcFFYImc5KZ3AyRlvwof74fx5Bn5esYdQSQ2gxzTwGyuyHJlh9HfYtXJB6QrtsPoDlQpnPJQJJxw+9ShtO7xKpYxBblF3zoG388ysryAnFUhF6YWajwsm0muWnawjQvfjsB3cQsP1/J+/x6+NCWkvO3zl5zgNKCb+9XfdKOSw2EaY=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
